import type { Metadata } from "next";
import { Syne } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/feature/navbar";
import Footer from "@/components/feature/footer";
import React from "react";
import Image from "next/image";

const syne = Syne({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={syne.className}>
    <Navbar/>
      <div className="fixed px-6 sm:px-8 md:px-16 lg:px-20 top-20 w-full h-full">
        <div className={"top-20 w-full h-full bg-contras rounded flex justify-between"}>
          <div className={"hidden h-full bg-white w-2/5 relative xl:flex items-center justify-center"}>
            <Image src={"/assets/img/profile/profile-1.png"} alt={""} className={"object-right object-cover"} fill />
          </div>
          <div className={"xl:w-3/5 px-12 pt-24 overflow-y-scroll"}>
            {children}
          </div>
        </div>
      </div>
    <Footer/>
    </body>
    </html>
  );
}
